In [16]:
import numpy as np
import pandas as pd

In [17]:
df = pd.read_csv('divvy_combined.csv')

In [18]:
df[1000000:1000005]

,Unnamed: 0,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
1000000,1000001,A014353AD7E49C66,electric_bike,2025-04-21 20:45:25.027,2025-04-21 20:51:35.458,Broadway & Cornelia Ave,13278,NaN,NaN,41.945529,-87.646439,41.96,-87.65,member
1000001,1000002,48CAAF076669AE7E,electric_bike,2025-04-10 23:10:01.378,2025-04-10 23:14:30.92,Broadway & Cornelia Ave,13278,NaN,NaN,41.945529,-87.646439,41.94,-87.66,member
1000002,1000003,9111767165A8ABA9,electric_bike,2025-04-24 06:56:38.238,2025-04-24 07:50:35.903,Broadway & Cornelia Ave,13278,NaN,NaN,41.945529,-87.646439,41.88,-87.63,member
1000003,1000004,41C49E6C3BE2AB83,electric_bike,2025-04-01 12:20:44.297,2025-04-01 12:24:36.758,Michigan Ave & Jackson Blvd,TA1309000002,NaN,NaN,41.877768,-87.624164,41.88,-87.63,member
1000004,1000005,CD32765DA8A73F22,electric_bike,2025-04-28 16:34:00.992,2025-04-28 16:34:20.675,Franklin St & Monroe St,TA1309000007,NaN,NaN,41.880317,-87.635185,41.88,-87.63,member

In [19]:
df.drop(columns=['Unnamed: 0'], inplace=True)

In [32]:
df.head(5)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length,hhmmss
0,6C960DEB4F78854E,electric_bike,2024-12-31 01:38:35.018,2024-12-31 01:48:45.775,Halsted St & Roscoe St,TA1309000025,Clark St & Winnemac Ave,TA1309000035,41.943632,-87.649083,41.973348,-87.667855,member,0 days 00:10:10.757000,00:10:10
1,C0913EEB2834E7A2,classic_bike,2024-12-21 18:41:26.478,2024-12-21 18:47:33.871,Clark St & Wellington Ave,TA1307000136,Halsted St & Roscoe St,TA1309000025,41.936497,-87.647539,41.943632,-87.649083,member,0 days 00:06:07.393000,00:06:07
2,848A37DD4723078A,classic_bike,2024-12-21 11:41:01.664,2024-12-21 11:52:45.094,Sheridan Rd & Montrose Ave,TA1307000107,Broadway & Barry Ave,13137,41.961670,-87.654640,41.937582,-87.644098,member,0 days 00:11:43.430000,00:11:43
3,3FA09C762ECB48BD,electric_bike,2024-12-26 13:07:27.526,2024-12-26 13:10:54.130,Aberdeen St & Jackson Blvd,13157,Green St & Randolph St*,chargingstx3,41.877726,-87.654787,41.883602,-87.648627,member,0 days 00:03:26.604000,00:03:26
4,E60317ADD1A87488,electric_bike,2024-12-13 15:17:55.063,2024-12-13 15:27:32.583,Paulina St & Flournoy St,KA1504000104,Fairfield Ave & Roosevelt Rd,KA1504000102,41.873061,-87.669135,41.866624,-87.694521,member,0 days 00:09:37.520000,00:09:37

### Calculate new columns

#### Ride Length

In [ ]:
df['started_at'] = pd.to_datetime(df['started_at'], format='mixed')
df['ended_at'] = pd.to_datetime(df['ended_at'], format='mixed')
df['ride_length'] = df['ended_at'] - df['started_at']
df.head(5)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length
0,6C960DEB4F78854E,electric_bike,2024-12-31 01:38:35.018,2024-12-31 01:48:45.775,Halsted St & Roscoe St,TA1309000025,Clark St & Winnemac Ave,TA1309000035,41.943632,-87.649083,41.973348,-87.667855,member,0 days 00:10:10.757000
1,C0913EEB2834E7A2,classic_bike,2024-12-21 18:41:26.478,2024-12-21 18:47:33.871,Clark St & Wellington Ave,TA1307000136,Halsted St & Roscoe St,TA1309000025,41.936497,-87.647539,41.943632,-87.649083,member,0 days 00:06:07.393000
2,848A37DD4723078A,classic_bike,2024-12-21 11:41:01.664,2024-12-21 11:52:45.094,Sheridan Rd & Montrose Ave,TA1307000107,Broadway & Barry Ave,13137,41.961670,-87.654640,41.937582,-87.644098,member,0 days 00:11:43.430000
3,3FA09C762ECB48BD,electric_bike,2024-12-26 13:07:27.526,2024-12-26 13:10:54.130,Aberdeen St & Jackson Blvd,13157,Green St & Randolph St*,chargingstx3,41.877726,-87.654787,41.883602,-87.648627,member,0 days 00:03:26.604000
4,E60317ADD1A87488,electric_bike,2024-12-13 15:17:55.063,2024-12-13 15:27:32.583,Paulina St & Flournoy St,KA1504000104,Fairfield Ave & Roosevelt Rd,KA1504000102,41.873061,-87.669135,41.866624,-87.694521,member,0 days 00:09:37.520000

In [34]:
# Convert ride_length to hh:mm:ss format
df["ride_length"] = df["ride_length"].apply(
    lambda x: f"{x.components.hours:02}:"
              f"{x.components.minutes:02}:"
              f"{x.components.seconds:02}"
)
df.drop(columns=['hhmmss'], inplace=True)
df.head(5)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length
0,6C960DEB4F78854E,electric_bike,2024-12-31 01:38:35.018,2024-12-31 01:48:45.775,Halsted St & Roscoe St,TA1309000025,Clark St & Winnemac Ave,TA1309000035,41.943632,-87.649083,41.973348,-87.667855,member,00:10:10
1,C0913EEB2834E7A2,classic_bike,2024-12-21 18:41:26.478,2024-12-21 18:47:33.871,Clark St & Wellington Ave,TA1307000136,Halsted St & Roscoe St,TA1309000025,41.936497,-87.647539,41.943632,-87.649083,member,00:06:07
2,848A37DD4723078A,classic_bike,2024-12-21 11:41:01.664,2024-12-21 11:52:45.094,Sheridan Rd & Montrose Ave,TA1307000107,Broadway & Barry Ave,13137,41.961670,-87.654640,41.937582,-87.644098,member,00:11:43
3,3FA09C762ECB48BD,electric_bike,2024-12-26 13:07:27.526,2024-12-26 13:10:54.130,Aberdeen St & Jackson Blvd,13157,Green St & Randolph St*,chargingstx3,41.877726,-87.654787,41.883602,-87.648627,member,00:03:26
4,E60317ADD1A87488,electric_bike,2024-12-13 15:17:55.063,2024-12-13 15:27:32.583,Paulina St & Flournoy St,KA1504000104,Fairfield Ave & Roosevelt Rd,KA1504000102,41.873061,-87.669135,41.866624,-87.694521,member,00:09:37

#### Day of week

In [42]:
# calculate the day of the week for each ride started_at
# df['day_of_week'] = df['started_at'].dt.day_name()

# encode the day of the week such that Monday=1, Tuesday=2, ..., Sunday=7
df['day_of_week'] = df['started_at'].dt.weekday + 1
df.head(5)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length,day_of_week
0,6C960DEB4F78854E,electric_bike,2024-12-31 01:38:35.018,2024-12-31 01:48:45.775,Halsted St & Roscoe St,TA1309000025,Clark St & Winnemac Ave,TA1309000035,41.943632,-87.649083,41.973348,-87.667855,member,00:10:10,2
1,C0913EEB2834E7A2,classic_bike,2024-12-21 18:41:26.478,2024-12-21 18:47:33.871,Clark St & Wellington Ave,TA1307000136,Halsted St & Roscoe St,TA1309000025,41.936497,-87.647539,41.943632,-87.649083,member,00:06:07,6
2,848A37DD4723078A,classic_bike,2024-12-21 11:41:01.664,2024-12-21 11:52:45.094,Sheridan Rd & Montrose Ave,TA1307000107,Broadway & Barry Ave,13137,41.961670,-87.654640,41.937582,-87.644098,member,00:11:43,6
3,3FA09C762ECB48BD,electric_bike,2024-12-26 13:07:27.526,2024-12-26 13:10:54.130,Aberdeen St & Jackson Blvd,13157,Green St & Randolph St*,chargingstx3,41.877726,-87.654787,41.883602,-87.648627,member,00:03:26,4
4,E60317ADD1A87488,electric_bike,2024-12-13 15:17:55.063,2024-12-13 15:27:32.583,Paulina St & Flournoy St,KA1504000104,Fairfield Ave & Roosevelt Rd,KA1504000102,41.873061,-87.669135,41.866624,-87.694521,member,00:09:37,5

In [43]:
df.shape

(5210775, 15)

In [44]:
df = df.dropna()
df.shape

(3523688, 15)

In [46]:
df = df[df['ride_length'] > '00:00:00']
df.shape

(3523427, 15)